//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace SMS_Sender.kr.co.hhi.officeeai {
    using System;
    //using System.Web.Services;
    using System.Diagnostics;
    //using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Web.Services.WebServiceBindingAttribute(Name="HHI_WebServiceSoap", Namespace="http://hhibts.com/WS/HHI_IFService")]
    public partial class HHI_WebService {  // : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        //private System.Threading.SendOrPostCallback Send_HO_TRANS_SMOperationCompleted;
        
        //private System.Threading.SendOrPostCallback Send_TXK0SMS2OperationCompleted;
        
        //private System.Threading.SendOrPostCallback Send_Push_OraOperationCompleted;
        
        //private bool useDefaultCredentialsSetExplicitly;
        
        ///// <remarks/>
        //public HHI_WebService() {
        //    this.Url = global::SMS_Sender.Properties.Settings.Default.SMS_Sender_kr_co_hhi_officeeai_HHI_WebService;
        //    if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
        //        this.UseDefaultCredentials = true;
        //        this.useDefaultCredentialsSetExplicitly = false;
        //    }
        //    else {
        //        this.useDefaultCredentialsSetExplicitly = true;
        //    }
        //}
        
        //public new string Url {
        //    get {
        //        return base.Url;
        //    }
        //    set {
        //        if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
        //                    && (this.useDefaultCredentialsSetExplicitly == false)) 
        //                    && (this.IsLocalFileSystemWebService(value) == false))) {
        //            base.UseDefaultCredentials = false;
        //        }
        //        base.Url = value;
        //    }
        //}
        
        //public new bool UseDefaultCredentials {
        //    get {
        //        return base.UseDefaultCredentials;
        //    }
        //    set {
        //        base.UseDefaultCredentials = value;
        //        this.useDefaultCredentialsSetExplicitly = true;
        //    }
        //}
        
        ///// <remarks/>
        //public event Send_HO_TRANS_SMCompletedEventHandler Send_HO_TRANS_SMCompleted;
        
        ///// <remarks/>
        //public event Send_TXK0SMS2CompletedEventHandler Send_TXK0SMS2Completed;
        
        ///// <remarks/>
        //public event Send_Push_OraCompletedEventHandler Send_Push_OraCompleted;
        
        ///// <remarks/>
        //[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hhibts.com/WS/HHI_IFService/HHI_WebService/Send_HO_TRANS_SM", RequestNamespace="http://hhibts.com/WS/HHI_IFService", ResponseNamespace="http://hhibts.com/WS/HHI_IFService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        //[return: System.Xml.Serialization.XmlElementAttribute("WSHO_TRANS_SM_RSP", Namespace="http://hhibts.com/WS/HO_TRANS_SM")]
        //public WSHO_TRANS_SM_RSP Send_HO_TRANS_SM([System.Xml.Serialization.XmlElementAttribute(Namespace="http://hhibts.com/WS/HO_TRANS_SM")] WSHO_TRANS_SM_REQ WSHO_TRANS_SM_REQ) {
        //    object[] results = this.Invoke("Send_HO_TRANS_SM", new object[] {
        //                WSHO_TRANS_SM_REQ});
        //    return ((WSHO_TRANS_SM_RSP)(results[0]));
        //}
        
        ///// <remarks/>
        //public void Send_HO_TRANS_SMAsync(WSHO_TRANS_SM_REQ WSHO_TRANS_SM_REQ) {
        //    this.Send_HO_TRANS_SMAsync(WSHO_TRANS_SM_REQ, null);
        //}
        
        ///// <remarks/>
        //public void Send_HO_TRANS_SMAsync(WSHO_TRANS_SM_REQ WSHO_TRANS_SM_REQ, object userState) {
        //    if ((this.Send_HO_TRANS_SMOperationCompleted == null)) {
        //        this.Send_HO_TRANS_SMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_HO_TRANS_SMOperationCompleted);
        //    }
        //    this.InvokeAsync("Send_HO_TRANS_SM", new object[] {
        //                WSHO_TRANS_SM_REQ}, this.Send_HO_TRANS_SMOperationCompleted, userState);
        //}
        
        //private void OnSend_HO_TRANS_SMOperationCompleted(object arg) {
        //    if ((this.Send_HO_TRANS_SMCompleted != null)) {
        //        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
        //        this.Send_HO_TRANS_SMCompleted(this, new Send_HO_TRANS_SMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        //    }
        //}
        
        ///// <remarks/>
        //[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hhibts.com/WS/HHI_IFService/HHI_WebService/Send_TXK0SMS2", RequestNamespace="http://hhibts.com/WS/HHI_IFService", ResponseNamespace="http://hhibts.com/WS/HHI_IFService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        //[return: System.Xml.Serialization.XmlElementAttribute("WSTXK0SMS2_RSP", Namespace="http://hhibts.com/WS/TXK0SMS2")]
        //public WSTXK0SMS2_RSP Send_TXK0SMS2([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://hhibts.com/WS/TXK0SMS2")] [System.Xml.Serialization.XmlArrayItemAttribute("TXK0SMS2", Namespace="", IsNullable=false)] WSTXK0SMS2_REQTXK0SMS2[] WSTXK0SMS2_REQ) {
        //    object[] results = this.Invoke("Send_TXK0SMS2", new object[] {
        //                WSTXK0SMS2_REQ});
        //    return ((WSTXK0SMS2_RSP)(results[0]));
        //}
        
        ///// <remarks/>
        //public void Send_TXK0SMS2Async(WSTXK0SMS2_REQTXK0SMS2[] WSTXK0SMS2_REQ) {
        //    this.Send_TXK0SMS2Async(WSTXK0SMS2_REQ, null);
        //}
        
        ///// <remarks/>
        //public void Send_TXK0SMS2Async(WSTXK0SMS2_REQTXK0SMS2[] WSTXK0SMS2_REQ, object userState) {
        //    if ((this.Send_TXK0SMS2OperationCompleted == null)) {
        //        this.Send_TXK0SMS2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_TXK0SMS2OperationCompleted);
        //    }
        //    this.InvokeAsync("Send_TXK0SMS2", new object[] {
        //                WSTXK0SMS2_REQ}, this.Send_TXK0SMS2OperationCompleted, userState);
        //}
        
        //private void OnSend_TXK0SMS2OperationCompleted(object arg) {
        //    if ((this.Send_TXK0SMS2Completed != null)) {
        //        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
        //        this.Send_TXK0SMS2Completed(this, new Send_TXK0SMS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        //    }
        //}
        
        ///// <remarks/>
        //[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hhibts.com/WS/HHI_IFService/HHI_WebService/Send_Push_Ora", RequestNamespace="http://hhibts.com/WS/HHI_IFService", ResponseNamespace="http://hhibts.com/WS/HHI_IFService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        //[return: System.Xml.Serialization.XmlElementAttribute("Ora_Push_RSP", Namespace="http://hhibts.com/WS/TXK0SMS2_Ora")]
        //public Ora_Push_RSP Send_Push_Ora([System.Xml.Serialization.XmlElementAttribute(Namespace="http://hhibts.com/WS/TXK0SMS2_Ora")] Ora_Push_REQ_TALK320 Ora_Push_REQ) {
        //    object[] results = this.Invoke("Send_Push_Ora", new object[] {
        //                Ora_Push_REQ});
        //    return ((Ora_Push_RSP)(results[0]));
        //}
        
        ///// <remarks/>
        //public void Send_Push_OraAsync(Ora_Push_REQ_TALK320 Ora_Push_REQ) {
        //    this.Send_Push_OraAsync(Ora_Push_REQ, null);
        //}
        
        ///// <remarks/>
        //public void Send_Push_OraAsync(Ora_Push_REQ_TALK320 Ora_Push_REQ, object userState) {
        //    if ((this.Send_Push_OraOperationCompleted == null)) {
        //        this.Send_Push_OraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Push_OraOperationCompleted);
        //    }
        //    this.InvokeAsync("Send_Push_Ora", new object[] {
        //                Ora_Push_REQ}, this.Send_Push_OraOperationCompleted, userState);
        //}
        
        //private void OnSend_Push_OraOperationCompleted(object arg) {
        //    if ((this.Send_Push_OraCompleted != null)) {
        //        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
        //        this.Send_Push_OraCompleted(this, new Send_Push_OraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        //    }
        //}
        
        /// <remarks/>
        //public new void CancelAsync(object userState) {
        //    base.CancelAsync(userState);
        //}
        
        //private bool IsLocalFileSystemWebService(string url) {
        //    if (((url == null) 
        //                || (url == string.Empty))) {
        //        return false;
        //    }
        //    System.Uri wsUri = new System.Uri(url);
        //    if (((wsUri.Port >= 1024) 
        //                && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
        //        return true;
        //    }
        //    return false;
        //}
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hhibts.com/WS/HO_TRANS_SM")]
    public partial class WSHO_TRANS_SM_REQ {
        
        private WSHO_TRANS_SM_REQHO_TRANS_SM hO_TRANS_SMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public WSHO_TRANS_SM_REQHO_TRANS_SM HO_TRANS_SM {
            get {
                return this.hO_TRANS_SMField;
            }
            set {
                this.hO_TRANS_SMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSHO_TRANS_SM_REQHO_TRANS_SM {
        
        private string m_REQSYSField;
        
        private string m_FROMField;
        
        private string m_SENDTOField;
        
        private string m_SUBJECTField;
        
        private string m_BODYField;
        
        /// <remarks/>
        public string M_REQSYS {
            get {
                return this.m_REQSYSField;
            }
            set {
                this.m_REQSYSField = value;
            }
        }
        
        /// <remarks/>
        public string M_FROM {
            get {
                return this.m_FROMField;
            }
            set {
                this.m_FROMField = value;
            }
        }
        
        /// <remarks/>
        public string M_SENDTO {
            get {
                return this.m_SENDTOField;
            }
            set {
                this.m_SENDTOField = value;
            }
        }
        
        /// <remarks/>
        public string M_SUBJECT {
            get {
                return this.m_SUBJECTField;
            }
            set {
                this.m_SUBJECTField = value;
            }
        }
        
        /// <remarks/>
        public string M_BODY {
            get {
                return this.m_BODYField;
            }
            set {
                this.m_BODYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hhibts.com/WS/TXK0SMS2_Ora")]
    public partial class Ora_Push_RSP {
        
        private string sTATUSField;
        
        private string dESCRIPTIONField;
        
        private string eRRORField;
        
        private string snField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
        
        /// <remarks/>
        public string SN {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hhibts.com/WS/TXK0SMS2_Ora")]
    public partial class Ora_Push_REQ_TALK320 {
        
        private string sEND_SABUNField;
        
        private string rCV_SABUNField;
        
        private string rCV_ORGField;
        
        private string sYS_TYPEField;
        
        private string sMS_GUBUNField;
        
        private string tITLEField;
        
        private string sEND_HPNOField;
        
        private string rCV_HPNOField;
        
        private string cONTENTField;
        
        private string aLIM_HEADField;
        
        private string fROM_SYSField;
        
        /// <remarks/>
        public string SEND_SABUN {
            get {
                return this.sEND_SABUNField;
            }
            set {
                this.sEND_SABUNField = value;
            }
        }
        
        /// <remarks/>
        public string RCV_SABUN {
            get {
                return this.rCV_SABUNField;
            }
            set {
                this.rCV_SABUNField = value;
            }
        }
        
        /// <remarks/>
        public string RCV_ORG {
            get {
                return this.rCV_ORGField;
            }
            set {
                this.rCV_ORGField = value;
            }
        }
        
        /// <remarks/>
        public string SYS_TYPE {
            get {
                return this.sYS_TYPEField;
            }
            set {
                this.sYS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string SMS_GUBUN {
            get {
                return this.sMS_GUBUNField;
            }
            set {
                this.sMS_GUBUNField = value;
            }
        }
        
        /// <remarks/>
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
            }
        }
        
        /// <remarks/>
        public string SEND_HPNO {
            get {
                return this.sEND_HPNOField;
            }
            set {
                this.sEND_HPNOField = value;
            }
        }
        
        /// <remarks/>
        public string RCV_HPNO {
            get {
                return this.rCV_HPNOField;
            }
            set {
                this.rCV_HPNOField = value;
            }
        }
        
        /// <remarks/>
        public string CONTENT {
            get {
                return this.cONTENTField;
            }
            set {
                this.cONTENTField = value;
            }
        }
        
        /// <remarks/>
        public string ALIM_HEAD {
            get {
                return this.aLIM_HEADField;
            }
            set {
                this.aLIM_HEADField = value;
            }
        }
        
        /// <remarks/>
        public string FROM_SYS {
            get {
                return this.fROM_SYSField;
            }
            set {
                this.fROM_SYSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hhibts.com/WS/TXK0SMS2")]
    public partial class WSTXK0SMS2_RSP {
        
        private string sTATUSField;
        
        private string dESCRIPTIONField;
        
        private string eRRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSTXK0SMS2_REQTXK0SMS2 {
        
        private string sEND_SABUNField;
        
        private string rCV_SABUNField;
        
        private string sYS_TYPEField;
        
        private string nOTICE_GUBUNField;
        
        private string tITLEField;
        
        private string sEND_HPNOField;
        
        private string rCV_HPNOField;
        
        private string cONTENTField;
        
        private string aLIM_HEADField;
        
        private string oNLY_SMSField;
        
        /// <remarks/>
        public string SEND_SABUN {
            get {
                return this.sEND_SABUNField;
            }
            set {
                this.sEND_SABUNField = value;
            }
        }
        
        /// <remarks/>
        public string RCV_SABUN {
            get {
                return this.rCV_SABUNField;
            }
            set {
                this.rCV_SABUNField = value;
            }
        }
        
        /// <remarks/>
        public string SYS_TYPE {
            get {
                return this.sYS_TYPEField;
            }
            set {
                this.sYS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string NOTICE_GUBUN {
            get {
                return this.nOTICE_GUBUNField;
            }
            set {
                this.nOTICE_GUBUNField = value;
            }
        }
        
        /// <remarks/>
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
            }
        }
        
        /// <remarks/>
        public string SEND_HPNO {
            get {
                return this.sEND_HPNOField;
            }
            set {
                this.sEND_HPNOField = value;
            }
        }
        
        /// <remarks/>
        public string RCV_HPNO {
            get {
                return this.rCV_HPNOField;
            }
            set {
                this.rCV_HPNOField = value;
            }
        }
        
        /// <remarks/>
        public string CONTENT {
            get {
                return this.cONTENTField;
            }
            set {
                this.cONTENTField = value;
            }
        }
        
        /// <remarks/>
        public string ALIM_HEAD {
            get {
                return this.aLIM_HEADField;
            }
            set {
                this.aLIM_HEADField = value;
            }
        }
        
        /// <remarks/>
        public string ONLY_SMS {
            get {
                return this.oNLY_SMSField;
            }
            set {
                this.oNLY_SMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hhibts.com/WS/HO_TRANS_SM")]
    public partial class WSHO_TRANS_SM_RSP {
        
        private string sTATUSField;
        
        private string dESCRIPTIONField;
        
        private string eRRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Send_HO_TRANS_SMCompletedEventHandler(object sender, Send_HO_TRANS_SMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_HO_TRANS_SMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_HO_TRANS_SMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSHO_TRANS_SM_RSP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSHO_TRANS_SM_RSP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Send_TXK0SMS2CompletedEventHandler(object sender, Send_TXK0SMS2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_TXK0SMS2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_TXK0SMS2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSTXK0SMS2_RSP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSTXK0SMS2_RSP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Send_Push_OraCompletedEventHandler(object sender, Send_Push_OraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Push_OraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Push_OraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ora_Push_RSP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ora_Push_RSP)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591